Algoritmo "Exercicio 4"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Kleber Petry
// Descrição   : Le um número e se for maior que 50 imprime a metade desse número.
// Autor(a)    : Luís Galete Faldão
// Data atual  : 10/04/2020
Var
// Seção de Declarações das variáveis 
n1: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite um numero: ")
leia (n1)
se n1 > 50 entao
 escreva ("A metade desse numero é: ", n1/2)
fimse

Fimalgoritmo